sudo: false
cache:
  directories:
  - $HOME/.gradle
language: groovy
jdk:
- openjdk8
install: true
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Jack Frosch"
  - GIT_EMAIL="jfrosch@objistics.com